### ISSUE TITLE
.cfg destination folder path not setable in option-window

### ISSUE THREAD

**Issue by Sheila69** [bgbennyboy/USB-Disk-Ejector#10]
When right click opening "Options" and modifying options there's no edit box for selection of a destination folder of .cfg file. 
For safety all these apps (like yours) go into an ACL protected folder within  %PROGRAMFILES%-folder on my system.
Execution of your app works great, but if the .cfg file cannot be specified, it cannot be written to the same folder as the EXE in this case.

[USB_Ejector_AccessDenied.zip](https://github.com/bgbennyboy/USB-Disk-Ejector/files/1503427/USB_Ejector_AccessDenied.zip)

I you don't plan to implement such an edit box (for an additional .cfg file, which would override the orignal existing in same folder) for the .cfg file, 
how can I specifiy the folder path for the .cfg file in registry?

I cannot fork and build your app, cause Visual Studio (C++) does not provide Delphi.

**Comment by bgbennyboy** [comment]
I cant let it be specified in options - because those settings are themselves saved into the .cfg file. 
It doesn't use the registry because its designed to be portable and not leave a footprint on the system.

However:
A command line switch to specify a different location for the cfg could be added.

**Comment by Sheila69** [comment]
thank you for your answer.
please add that command line switch. 
unfortunately it is impossible for me to build the binary

**Comment by bgbennyboy** [comment]
Fixed in [https://github.com/bgbennyboy/USB-Disk-Ejector/commit/0afab0b6aa22526935ec15c58bb7e1c939cb691d](url)
There's a new release on my site with the changes.

**Comment by Sheila69** [comment]
thank you very much! works perfectly! great!
