### ISSUE TITLE
Thanks for the program!

### ISSUE THREAD

**Issue by mrkaban** [bgbennyboy/USB-Disk-Ejector#17]
Hello, thanks for the program under the GNU GPL v2 license! Added it to the Russian-language site about free software ([here is the link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D1%83%D1%82%D0%B8%D0%BB%D0%B8%D1%82%D1%8B/%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0/usb-disk-ejector.html)).

Tell me, please, is it planned to translate the program into different languages?

**Comment by bgbennyboy** [comment]
Its been on the todo list for a long time, but its not currently possible
