### ISSUE TITLE
check out the Wikis USB_Disk_Eject.cfg

### ISSUE THREAD

**Issue by blackcrack** [bgbennyboy/USB-Disk-Ejector#19]
Hi @bgbennyboy ,
check out the 
[https://github.com/bgbennyboy/USB-Disk-Ejector/wiki/USB_Disk_Eject.cfg](https://github.com/bgbennyboy/USB-Disk-Ejector/wiki/USB_Disk_Eject.cfg)

if all possibility's to be in ..

thy :)
best
Blacky

**Comment by bgbennyboy** [comment]
Thank you for this but I'm not sure that the cfg needs documenting as all the settings stored in it are changed in the GUI. Its not really designed to be user edited (although this is possible of course).

**Comment by blackcrack** [comment]
it works wonderful if i use it at the usb-stick, because is it very nice if all works so far and is up to date .. :)
