### ISSUE TITLE
Exit Code is always 0

### ISSUE THREAD

**Issue by ciphernemo** [bgbennyboy/USB-Disk-Ejector#23]
I am calling USB Disk Ejector from PowerShell with a Process-Start command. I'm then catching the exit code to determine if the device eject was successful or not. However, USB Disk Ejector always returns an exit code of zero, regardless of whether it successfully ejected a device or not. Is it possible to have the exit code return a different value depending upon whether the eject command was successful? That way I could run it in a do loop with some sleep time in-between and check for exit codes until my drive successfully ejects.

Thank you!

BTW, thanks for creating and sharing this, it's working well so far in ejecting USB drives.

**Comment by ciphernemo** [comment]
For those using USB Disk Ejector in PowerShell and looking for a workaround, here's an example to keep trying the eject if the drive letter you're ejecting is still available:

```
$targetDrive = "F:"
while (Test-Path -Path "$targetDrive\")
{ 
	# sleep for 10 minutes
	Start-Sleep -seconds 600
	# eject the drive
	Start-Process -FilePath ".\USB_Disk_Eject.exe" -ArgumentList "/REMOVELETTER $targetDrive" -WindowStyle Hidden -PassThru -Wait | out-null
}

```

**Comment by bgbennyboy** [comment]
Because its a GUI rather than console application output to stdout unfortunately doesn't work. Its a Windows issue with GUI programs. I've looked into a few hacks over the years to address this but there were always problems.
For a true command line alternative I would recommend [RemoveDrive.](https://www.uwe-sieber.de/drivetools_e.html)

**Comment by ciphernemo** [comment]
bgbennyboy, thanks for the explanation. 😊 No worries since I found a work around.
