### ISSUE TITLE
HDD does not stop spinning

### ISSUE THREAD

**Issue by VooDisss** [bgbennyboy/USB-Disk-Ejector#24]
3.5" 12TB HDD is being powered by external 12V PSU and 5V 3.1 connection plugged to PC.
Unmount is pressed, the HDD is prepared for "safe unplug" but it still spins (even when I unplug USB from PC). Then i connect my usb back into PC and it gets recognised as normal. I cannot unplug my 12V because it will engage "Power-off Retract Count" into my HDD S.M.A.R.T. statistics.

This needs fixed, but I will look for alternative apps. Thanks to the developers, it seemed like a nice simple UI.

**Comment by bgbennyboy** [comment]
I would guess that the spinning is a hardware thing. Does it do the same when ejected using Windows' safely remove dialog? Behind the scenes the program is using the same api, so it should behave as windows does.

**Comment by VooDisss** [comment]
Hi, I just noticed it was my problem, I thought that my HDD is still spinning because of the vibrations from PC... The app works now, but I'm not sure why on my brand new WD UltraStar HC520 HUH721212ALE600 12TB the S.M.A.R.T. C0 (Power-off Retract Count) is the same as C1 (Load/Unload Cycle Count) and increases together, while on my other old WD 1TB C0 increases only if the power to the HDD has been cut improperly... 

Maybe it is as it should be, I could not find how to make C0 not increase, I'm using a proper lab power supply as 12V to my USB 3.0 to SATA3 adapter...

You can close it as solved, if you don't have something to comment more about this. Thanks!
