### ISSUE TITLE
Please allow using hotkeys combining Start button ( you can include a checkbox for it if you want) 

### ISSUE THREAD

**Issue by cool-RR** [bgbennyboy/USB-Disk-Ejector#4]

**Comment by bgbennyboy** [comment]
I'm not sure its possible to use the start key as part of global hotkeys but I'll look into it

**Comment by bgbennyboy** [comment]
Looked into it - Windows guidelines are not to use the windows key as part of global hotkeys as they are reserved for the os and can change between windows versions. I wont be adding this, sorry.
