### ISSUE TITLE
Please make esc minimize the window

### ISSUE THREAD

**Issue by cool-RR** [bgbennyboy/USB-Disk-Ejector#5]

**Comment by Denisov21** [comment]
+1

**Comment by bgbennyboy** [comment]
This is doable. Adding it now

**Comment by bgbennyboy** [comment]
Added in latest commit

**Comment by cool-RR** [comment]
Awesome! Can you please let me know when you're releasing a binary with
this fix?

**Comment by bgbennyboy** [comment]
I'm going to try and go through my backlog of things to fix and add so it'll be a few weeks I imagine

**Comment by Karsonito** [comment]
Hello! I'm wating for binary version too. Please share it

**Comment by bgbennyboy** [comment]
I've just uploaded a new binary, sorry it took so long.

**Comment by Karsonito** [comment]
Thank you very much! )

**Comment by cool-RR** [comment]
Thanks a lot! Confirmed it's working here!
