### ISSUE TITLE
Improvements and suggestions

### ISSUE THREAD

**Issue by ClaudioCas** [bgbennyboy/USB-Disk-Ejector#7]
Dear Benny,
thanks for your great software. I have some suggestions:
- add support for Windows Key for HotKey combination
- add "toggle function" with HotKey combination (hide the form if is shown, show if it is not visible)
- add option to show the program only in NotifyArea and not in Taskbar

Claudio

**Comment by bgbennyboy** [comment]
Thanks for the feedback:

- Unfortunately the Windows key cant be used for hotkeys as Windows reserves it for its own global hotkeys
- Toggle is a good idea
- Hiding from the taskbar is possible, I'll look into it when i get time

**Comment by ClaudioCas** [comment]
Thanks for your reply.
Here some tips to use Windows Key in delphi 
http://stackoverflow.com/questions/327880/thotkey-with-win-key-support

**Comment by bgbennyboy** [comment]
I wont be adding Windows Key support as its against the Windows guidelines to use the windows key in hotkeys.
I've just added the toggle function - thanks for the suggestion.
There's already the 'close to tray', 'minimize to tray' and 'start minimized' options so I dont think another option to hide from the taskbar is needed. With those options it'll only show in the taskbar while you're ejecting a disk - which seems reasonable and what one would expect.
