### ISSUE TITLE
Option to eject via left click

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [bgbennyboy/USB-Disk-Ejector#9]
With this option you can eject USB device via left click at tray when the main window is hidden.

**Comment by bgbennyboy** [comment]
Currently, right clicking the tray icon and choose 'eject' lets you eject from the tray while left clicking the icon restores the program.

If you mean that those actions should be reversed then thats not what most users would expect. If you mean that 1 left click should bring up an eject menu then I suppose its possible but I'd have to add an additional item for restoring the main window and options and ini settings to manage it all. I dont really see the benefit of this I'm afraid.
